### ISSUE TITLE
Dataset request

### ISSUE THREAD

**Issue by ShiroDoMain** [wuchengyu123/MMFusion#1]
Hi, this is a awesome project! I'd like to try reproducing the code, but I don't have enough data. Is there a way to apply for the dataset, or could you release a pre-trained model?

**Comment by wuchengyu123** [comment]
> Hi, this is a awesome project! I'd like to try reproducing the code, but I don't have enough data. Is there a way to apply for the dataset, or could you release a pre-trained model?

Thank you for your attention. I am sorry that we do not have the rights to make the hospital's dataset public available due to the control of ethical principles. The pretrained model will be released later on December, I am very busy right now. Thank you for your understanding!
